### PR TITLE
Add chord upload

### PR DESCRIPTION
**Pull request by bittujoju**
image

### CODE REVIEW

**Comment by jdestgermain** [comment]
Okay, so I took a look. 

Because chord libraries on dot i/o are additive, I think if the user uploads a chord file the return file should only include the new chords. What do you think?

Also, if we don't do that, then we will need to fix some things as I noticed that some of the chords output from my uploaded chord library (noticeably any multi word phrases) will output with "Space" in them (also saw some that are undefined).  But that being said, I don't think the output file needs to include the existing chords so this shouldn't be a problem. 

Example issue chord that was regurgitated incorrectly

image

**Comment by jdestgermain** [comment]
Once complete, this will close #8

**Comment by jdestgermain** [comment]
And to be clear, what I meant was that the chords from the chord library shouldn't be included in the generated CSV, in my opinion.  Although it doesn't hurt, it seems to be not adding extra value and could lead to errors like the one I showed

**Comment by bittujoju** [comment]
> And to be clear, what I meant was that the chords from the chord library shouldn't be included in the generated CSV, in my opinion. Although it doesn't hurt, it seems to be not adding extra value and could lead to errors like the one I showed

that makes sense. I updated it to only create csv with new chords.

**Comment by bittujoju** [comment]
> Okay, so I took a look.
> 
> Because chord libraries on dot i/o are additive, I think if the user uploads a chord file the return file should only include the new chords. What do you think?
> 
> Also, if we don't do that, then we will need to fix some things as I noticed that some of the chords output from my uploaded chord library (noticeably any multi word phrases) will output with "Space" in them (also saw some that are undefined). But that being said, I don't think the output file needs to include the existing chords so this shouldn't be a problem.
> 
> Example issue chord that was regurgitated incorrectly
> 
> image

oops. This is from the change I made just now. Fixing it.

**Comment by bittujoju** [comment]
I'll remove the Work in progress tag once all the fixes are added.

**Pull request merged**
